// <auto-generated />
using System;
using GestionExpropaciones.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionExpropaciones.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250220084134_Other_Models_Creation")]
    partial class Other_Models_Creation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionExpropaciones.Models.AppraisalModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Appraisal_Date")
                        .HasColumnType("date")
                        .HasColumnName("Appraisal_Date");

                    b.Property<string>("Appraisal_Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Appraisal_Number");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Comments");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Created_By");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("date")
                        .HasColumnName("Created_On");

                    b.Property<double>("Estimated_Appraisal")
                        .HasColumnType("float")
                        .HasColumnName("Estimated_Appraisal");

                    b.Property<int>("FileId")
                        .HasColumnType("int")
                        .HasColumnName("FileId");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Active");

                    b.Property<int>("Payment_Status")
                        .HasColumnType("int")
                        .HasColumnName("Payment_Status");

                    b.Property<double>("Real_Appraisal")
                        .HasColumnType("float")
                        .HasColumnName("Real_Appraisal");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("Appraisals", (string)null);
                });

            modelBuilder.Entity("GestionExpropaciones.Models.ExpropiatedPropertyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Area")
                        .HasColumnType("int")
                        .HasColumnName("Area");

                    b.Property<string>("Cadastral_Map")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Cadastral_Map");

                    b.Property<int>("Canton")
                        .HasColumnType("int")
                        .HasColumnName("Canton");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Comments");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Created_By");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("date")
                        .HasColumnName("Created_On");

                    b.Property<string>("District")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("District");

                    b.Property<int>("FileId")
                        .HasColumnType("int")
                        .HasColumnName("FileId");

                    b.Property<string>("Folio_Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Folio_Number");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Active");

                    b.Property<int>("Province")
                        .HasColumnType("int")
                        .HasColumnName("Province");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("ExpropiatedProperties", (string)null);
                });

            modelBuilder.Entity("GestionExpropaciones.Models.FileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2100)")
                        .HasColumnName("Comments");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Created_By");

                    b.Property<int>("Fase")
                        .HasColumnType("int")
                        .HasColumnName("Fase");

                    b.Property<DateTime?>("Finish_Date")
                        .HasColumnType("date")
                        .HasColumnName("Finish_Date");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Active");

                    b.Property<string>("Km")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Km");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Number");

                    b.Property<string>("Project_Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Project_Number");

                    b.Property<int>("Section")
                        .HasColumnType("int")
                        .HasColumnName("Section");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("date")
                        .HasColumnName("Start_Date");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("GestionExpropaciones.Models.OwnerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Address");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Comments");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Created_By");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("date")
                        .HasColumnName("Created_On");

                    b.Property<string>("Email1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email1");

                    b.Property<string>("Email12")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email12");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("First_Name");

                    b.Property<string>("Identification_Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Identification_Number");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Active");

                    b.Property<string>("Last_Name1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Last_Name1");

                    b.Property<string>("Last_Name2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Last_Name2");

                    b.Property<int>("Owner_Type")
                        .HasColumnType("int")
                        .HasColumnName("Owner_Type");

                    b.Property<string>("Phone1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Phone1");

                    b.Property<string>("Phone2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Phone2");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("Owners", (string)null);
                });

            modelBuilder.Entity("GestionExpropaciones.Models.OwnerPropertyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Annotation")
                        .HasColumnType("int")
                        .HasColumnName("Annotation");

                    b.Property<int>("Area")
                        .HasColumnType("int")
                        .HasColumnName("Area");

                    b.Property<string>("CadastralMap_Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CadastralMap_Number");

                    b.Property<int>("Canton")
                        .HasColumnType("int")
                        .HasColumnName("Canton");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Comments");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Created_By");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("date")
                        .HasColumnName("Created_On");

                    b.Property<string>("District")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("District");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<string>("Folio_Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Folio_Number");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Active");

                    b.Property<int>("Province")
                        .HasColumnType("int")
                        .HasColumnName("Province");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("OwnerProperties", (string)null);
                });

            modelBuilder.Entity("GestionExpropaciones.Models.PaperWorkModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Comments");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Created_By");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("date")
                        .HasColumnName("Created_On");

                    b.Property<DateTime>("Document_Date")
                        .HasColumnType("date")
                        .HasColumnName("Document_Date");

                    b.Property<string>("Document_Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Document_Number");

                    b.Property<int>("FileId")
                        .HasColumnType("int")
                        .HasColumnName("FileId");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Active");

                    b.Property<int>("PaperWork_type")
                        .HasColumnType("int")
                        .HasColumnName("PaperWork_type");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("PaperWorks", (string)null);
                });

            modelBuilder.Entity("GestionExpropaciones.Models.ProjectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2100)")
                        .HasColumnName("Comments");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Created_By");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("date")
                        .HasColumnName("Created_On");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Number");

                    b.HasKey("Id");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("GestionExpropaciones.Models.AppraisalModel", b =>
                {
                    b.HasOne("GestionExpropaciones.Models.FileModel", "File")
                        .WithMany("Appraisals")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("GestionExpropaciones.Models.ExpropiatedPropertyModel", b =>
                {
                    b.HasOne("GestionExpropaciones.Models.FileModel", "File")
                        .WithMany("ExpropiatedProperties")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("GestionExpropaciones.Models.OwnerModel", b =>
                {
                    b.HasOne("GestionExpropaciones.Models.FileModel", "File")
                        .WithMany("Owners")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("GestionExpropaciones.Models.OwnerPropertyModel", b =>
                {
                    b.HasOne("GestionExpropaciones.Models.FileModel", "File")
                        .WithMany("OwnerProperties")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("GestionExpropaciones.Models.PaperWorkModel", b =>
                {
                    b.HasOne("GestionExpropaciones.Models.FileModel", "File")
                        .WithMany("PaperWorks")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("GestionExpropaciones.Models.FileModel", b =>
                {
                    b.Navigation("Appraisals");

                    b.Navigation("ExpropiatedProperties");

                    b.Navigation("OwnerProperties");

                    b.Navigation("Owners");

                    b.Navigation("PaperWorks");
                });
#pragma warning restore 612, 618
        }
    }
}
